#!/bin/bash
set -e  # Exit immediately if any command exits with a non-zero status

# Get the root of the git repository
ROOT_DIR=$(git rev-parse --show-toplevel)

# Get the list of changed files
CHANGED_FILES=$(git diff --cached --name-only)

# Filter out test.c
FILES_TO_CHECK=$(echo "$CHANGED_FILES" | grep -v 'test.c')

if [ -z "$FILES_TO_CHECK" ]; then
    echo "No files to check with Norminette."
    exit 0
fi

# Run Norminette
echo "Running Norminette..."
make -C "$ROOT_DIR" norminette FILES="$FILES_TO_CHECK"

# Build the project
echo "Building the project..."
make -C "$ROOT_DIR"
make -C "$ROOT_DIR" fclean

# # Run cppcheck
# echo "Running cppcheck..."
# make -C "$ROOT_DIR" cppcheck

# Run Clang Static Analyzer
echo "Running Clang Static Analyzer..."
make -C "$ROOT_DIR" clang_analyzer

